server:
  port: 8080

eureka:
  client:
    #是否将自己注册到eureka
    register-with-eureka: false
    #是否从eurreka server中获取信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

  server:
    enable-self-preservation: false



management:
 endpoints:
  web:
    exposure:
      include: "*"
    base-path: /a

info:
 phone: 18049638730
 email: zy1270157082@outlook.com